### PR TITLE
[SDK-509] Internal events should be dependent on their specific feature consent

### PR DESCRIPTION
**Pull request by turtledreams**
SDK-509:
- Deleted `check_consent("events")` check

### CODE REVIEW

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
While this is a good catch for a related consent bug, this does not imeplement the requested task.

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
slightly tweak this

**Comment by turtledreams** [comment]
- Changed vars with enums

- Redacted the exclamations in changelog and made it a simpler enty

**Comment by ArtursKadikis** [comment]
@ar2rsawseen any potential issues with this?

**Review by ar2rsawseen — APPROVED** [review]

**Pull request merged**
