### PR TITLE
[SDK-507] No Consent Check at Merging

### PR DESCRIPTION
**Pull request by turtledreams**
SDK-507:
- Consent check deleted
- `lastParams.change_id = arguments` deleted to not create conflict

### CODE REVIEW

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
I think that probably part of this PR we should also remove:
https://github.com/Countly/countly-sdk-web/blob/master/lib/countly.js#L421-L424

**Comment by ArtursKadikis** [comment]
@ar2rsawseen what do you think about that?

**Comment by turtledreams** [comment]
Makes sense, have contemplated on that too, curious if it has some possible future value.

**Comment by ar2rsawseen** [comment]
@ArtursKadikis yeah that all parts referencing lastParams.change_id can be removed :)

**Review by ArtursKadikis — APPROVED** [review]

**Pull request merged**
